// Auto-generated. Do not edit!

// (in-package face_learning_actions.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class FaceDetectionGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.detect_face = null;
    }
    else {
      if (initObj.hasOwnProperty('detect_face')) {
        this.detect_face = initObj.detect_face
      }
      else {
        this.detect_face = false;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type FaceDetectionGoal
    // Serialize message field [detect_face]
    bufferOffset = _serializer.bool(obj.detect_face, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type FaceDetectionGoal
    let len;
    let data = new FaceDetectionGoal(null);
    // Deserialize message field [detect_face]
    data.detect_face = _deserializer.bool(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 1;
  }

  static datatype() {
    // Returns string type for a message object
    return 'face_learning_actions/FaceDetectionGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '313be249fa98e9c3d08e0b3b5d828c25';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #goal
    bool detect_face
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new FaceDetectionGoal(null);
    if (msg.detect_face !== undefined) {
      resolved.detect_face = msg.detect_face;
    }
    else {
      resolved.detect_face = false
    }

    return resolved;
    }
};

module.exports = FaceDetectionGoal;
