// Auto-generated. Do not edit!

// (in-package face_learning_actions.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class FaceDetectionFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.number_of_faces = null;
    }
    else {
      if (initObj.hasOwnProperty('number_of_faces')) {
        this.number_of_faces = initObj.number_of_faces
      }
      else {
        this.number_of_faces = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type FaceDetectionFeedback
    // Serialize message field [number_of_faces]
    bufferOffset = _serializer.int32(obj.number_of_faces, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type FaceDetectionFeedback
    let len;
    let data = new FaceDetectionFeedback(null);
    // Deserialize message field [number_of_faces]
    data.number_of_faces = _deserializer.int32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'face_learning_actions/FaceDetectionFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'efbc928311d5f00763e8c68b0f8a8609';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #feedback
    int32 number_of_faces
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new FaceDetectionFeedback(null);
    if (msg.number_of_faces !== undefined) {
      resolved.number_of_faces = msg.number_of_faces;
    }
    else {
      resolved.number_of_faces = 0
    }

    return resolved;
    }
};

module.exports = FaceDetectionFeedback;
