(cl:defpackage face_learning_actions-msg
  (:use )
  (:export
   "<FACEDETECTIONACTION>"
   "FACEDETECTIONACTION"
   "<FACEDETECTIONACTIONFEEDBACK>"
   "FACEDETECTIONACTIONFEEDBACK"
   "<FACEDETECTIONACTIONGOAL>"
   "FACEDETECTIONACTIONGOAL"
   "<FACEDETECTIONACTIONRESULT>"
   "FACEDETECTIONACTIONRESULT"
   "<FACEDETECTIONFEEDBACK>"
   "FACEDETECTIONFEEDBACK"
   "<FACEDETECTIONGOAL>"
   "FACEDETECTIONGOAL"
   "<FACEDETECTIONRESULT>"
   "FACEDETECTIONRESULT"
  ))

