; Auto-generated. Do not edit!


(cl:in-package face_learning_actions-msg)


;//! \htmlinclude FaceDetectionGoal.msg.html

(cl:defclass <FaceDetectionGoal> (roslisp-msg-protocol:ros-message)
  ((detect_face
    :reader detect_face
    :initarg :detect_face
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass FaceDetectionGoal (<FaceDetectionGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <FaceDetectionGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'FaceDetectionGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name face_learning_actions-msg:<FaceDetectionGoal> is deprecated: use face_learning_actions-msg:FaceDetectionGoal instead.")))

(cl:ensure-generic-function 'detect_face-val :lambda-list '(m))
(cl:defmethod detect_face-val ((m <FaceDetectionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader face_learning_actions-msg:detect_face-val is deprecated.  Use face_learning_actions-msg:detect_face instead.")
  (detect_face m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <FaceDetectionGoal>) ostream)
  "Serializes a message object of type '<FaceDetectionGoal>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'detect_face) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <FaceDetectionGoal>) istream)
  "Deserializes a message object of type '<FaceDetectionGoal>"
    (cl:setf (cl:slot-value msg 'detect_face) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<FaceDetectionGoal>)))
  "Returns string type for a message object of type '<FaceDetectionGoal>"
  "face_learning_actions/FaceDetectionGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'FaceDetectionGoal)))
  "Returns string type for a message object of type 'FaceDetectionGoal"
  "face_learning_actions/FaceDetectionGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<FaceDetectionGoal>)))
  "Returns md5sum for a message object of type '<FaceDetectionGoal>"
  "313be249fa98e9c3d08e0b3b5d828c25")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'FaceDetectionGoal)))
  "Returns md5sum for a message object of type 'FaceDetectionGoal"
  "313be249fa98e9c3d08e0b3b5d828c25")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<FaceDetectionGoal>)))
  "Returns full string definition for message of type '<FaceDetectionGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal~%bool detect_face~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'FaceDetectionGoal)))
  "Returns full string definition for message of type 'FaceDetectionGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal~%bool detect_face~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <FaceDetectionGoal>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <FaceDetectionGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'FaceDetectionGoal
    (cl:cons ':detect_face (detect_face msg))
))
