// Generated by gencpp from file face_learning_actions/FaceDetectionResult.msg
// DO NOT EDIT!


#ifndef FACE_LEARNING_ACTIONS_MESSAGE_FACEDETECTIONRESULT_H
#define FACE_LEARNING_ACTIONS_MESSAGE_FACEDETECTIONRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace face_learning_actions
{
template <class ContainerAllocator>
struct FaceDetectionResult_
{
  typedef FaceDetectionResult_<ContainerAllocator> Type;

  FaceDetectionResult_()
    : success(false)  {
    }
  FaceDetectionResult_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::face_learning_actions::FaceDetectionResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::face_learning_actions::FaceDetectionResult_<ContainerAllocator> const> ConstPtr;

}; // struct FaceDetectionResult_

typedef ::face_learning_actions::FaceDetectionResult_<std::allocator<void> > FaceDetectionResult;

typedef boost::shared_ptr< ::face_learning_actions::FaceDetectionResult > FaceDetectionResultPtr;
typedef boost::shared_ptr< ::face_learning_actions::FaceDetectionResult const> FaceDetectionResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::face_learning_actions::FaceDetectionResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::face_learning_actions::FaceDetectionResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace face_learning_actions

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'face_learning_actions': ['/home/hanna/action_ws/devel/share/face_learning_actions/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::face_learning_actions::FaceDetectionResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::face_learning_actions::FaceDetectionResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::face_learning_actions::FaceDetectionResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::face_learning_actions::FaceDetectionResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::face_learning_actions::FaceDetectionResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::face_learning_actions::FaceDetectionResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::face_learning_actions::FaceDetectionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::face_learning_actions::FaceDetectionResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::face_learning_actions::FaceDetectionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "face_learning_actions/FaceDetectionResult";
  }

  static const char* value(const ::face_learning_actions::FaceDetectionResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::face_learning_actions::FaceDetectionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#result\n\
bool success\n\
";
  }

  static const char* value(const ::face_learning_actions::FaceDetectionResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::face_learning_actions::FaceDetectionResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FaceDetectionResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::face_learning_actions::FaceDetectionResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::face_learning_actions::FaceDetectionResult_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FACE_LEARNING_ACTIONS_MESSAGE_FACEDETECTIONRESULT_H
