// Generated by gencpp from file face_learning_actions/FaceDetectionActionGoal.msg
// DO NOT EDIT!


#ifndef FACE_LEARNING_ACTIONS_MESSAGE_FACEDETECTIONACTIONGOAL_H
#define FACE_LEARNING_ACTIONS_MESSAGE_FACEDETECTIONACTIONGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <face_learning_actions/FaceDetectionGoal.h>

namespace face_learning_actions
{
template <class ContainerAllocator>
struct FaceDetectionActionGoal_
{
  typedef FaceDetectionActionGoal_<ContainerAllocator> Type;

  FaceDetectionActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  FaceDetectionActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::face_learning_actions::FaceDetectionGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::face_learning_actions::FaceDetectionActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::face_learning_actions::FaceDetectionActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct FaceDetectionActionGoal_

typedef ::face_learning_actions::FaceDetectionActionGoal_<std::allocator<void> > FaceDetectionActionGoal;

typedef boost::shared_ptr< ::face_learning_actions::FaceDetectionActionGoal > FaceDetectionActionGoalPtr;
typedef boost::shared_ptr< ::face_learning_actions::FaceDetectionActionGoal const> FaceDetectionActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::face_learning_actions::FaceDetectionActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::face_learning_actions::FaceDetectionActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace face_learning_actions

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'face_learning_actions': ['/home/hanna/action_ws/devel/share/face_learning_actions/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::face_learning_actions::FaceDetectionActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::face_learning_actions::FaceDetectionActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::face_learning_actions::FaceDetectionActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::face_learning_actions::FaceDetectionActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::face_learning_actions::FaceDetectionActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::face_learning_actions::FaceDetectionActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::face_learning_actions::FaceDetectionActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fcec4f59938e9c77d5cafd1a1876c3fe";
  }

  static const char* value(const ::face_learning_actions::FaceDetectionActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfcec4f59938e9c77ULL;
  static const uint64_t static_value2 = 0xd5cafd1a1876c3feULL;
};

template<class ContainerAllocator>
struct DataType< ::face_learning_actions::FaceDetectionActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "face_learning_actions/FaceDetectionActionGoal";
  }

  static const char* value(const ::face_learning_actions::FaceDetectionActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::face_learning_actions::FaceDetectionActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalID goal_id\n\
FaceDetectionGoal goal\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: actionlib_msgs/GoalID\n\
# The stamp should store the time at which this goal was requested.\n\
# It is used by an action server when it tries to preempt all\n\
# goals that were requested before a certain time\n\
time stamp\n\
\n\
# The id provides a way to associate feedback and\n\
# result message with specific goal requests. The id\n\
# specified must be unique.\n\
string id\n\
\n\
\n\
================================================================================\n\
MSG: face_learning_actions/FaceDetectionGoal\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#goal\n\
bool detect_face\n\
";
  }

  static const char* value(const ::face_learning_actions::FaceDetectionActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::face_learning_actions::FaceDetectionActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FaceDetectionActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::face_learning_actions::FaceDetectionActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::face_learning_actions::FaceDetectionActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::face_learning_actions::FaceDetectionGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FACE_LEARNING_ACTIONS_MESSAGE_FACEDETECTIONACTIONGOAL_H
